# The Docker image that will be used to build your app
image: ruby:3.1.3-bullseye
# Functions that should be executed before the build script is run
before_script:
  - curl -fsSL https://raw.githubusercontent.com/tj/n/master/bin/n | bash -s lts
  - npm ci
  - gem install bundler
  - bundle install
pages:
  script:
    - npm run build
    - cp -r _site public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
