title: DigitalService Engineering
description: Open Source repository overview
url: https://digitalservicebund.github.io

collections:
  projects:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
  - update-projects-md.js
  - public
