title: DigitalService Open Source
description: Open Source repository overview
url: https://digitalservicebund.github.io

plugins:
  - jekyll-postcss

postcss:
  cache: false

collections:
  projects:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"

include:
  - security.txt

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - SECURITY.md
  - postcss.config.js
  - tailwind.config.js
  - netlify.toml
  - update-projects-md.js
  - public
