name: Deploy to github pages

concurrency: Deployment

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Setup Node
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
        with:
          node-version-file: '.nvmrc'
          cache: "npm"

      - name: validate github workflow files
        uses: digitalservice4germany/github-actions/github-actions-linter@9f123efaec38519ca50547171b73a33564318758

      - uses: ruby/setup-ruby@e92b7971f0f3a08d2cf29cceb1d82d4c704a2a78
        with:
          bundler-cache: true

      - name: Install node modules
        run: npm ci

      - name: Build page
        run: npm run build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@a117e4aa1fb4854d021546d2abdfac95be568a3a
        with:
          target_branch: gh-pages
          build_dir: _site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
