name: Deploy to github pages

concurrency: Deployment

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version-file: ".nvmrc"
      #     cache: "npm"

      - name: validate github workflow files
        uses: digitalservicebund/github-actions-linter@dccac3ada437947aada4bc901daff08ceb87c3f1 # v0.1.11

      - uses: ruby/setup-ruby@d37167af451eb51448db3354e1057b75c4b268f7
        with:
          bundler-cache: true

      - name: Install node modules
        run: npm ci

      - name: Build page
        run: npm run build:production

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@c05ee637ec73429400a359430db8e5629f3f2564
        with:
          target_branch: gh-pages
          build_dir: _site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
