name: Sync to Open CoDE

concurrency: Sync

on:
  push:
    branches: [main]

jobs:
  to_opencode:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps: # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sync repo to OpenCoDE
        uses: pixta-dev/repository-mirroring-action@674e65a7d483ca28dafaacba0d07351bdcc8bd75
        with:
          target_repo_url: git@gitlab.opencode.de:digitalservicebund/digitalservicebund.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
