name: Sync to Open CoDE

concurrency: Sync

on:
  push:
    branches: [main]

jobs:
  to_opencode:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps: # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false   
      
      - name: Sync repo to OpenCoDE
        shell: bash
        run: |
          eval $(ssh-agent)
          echo "$SSH_KEY" | sed '$ s/\n$//' | ssh-add -
          git -T -vvvv git@gitlab.opencode.de
          git remote add opencode git@gitlab.opencode.de:digitalservicebund/digitalservicebund.git
          git push opencode -f
        env:
          SSH_KEY: secrets.GITLAB_SSH_PRIVATE_KEY
