name: Sync to Open CoDE

concurrency: Sync

on:
  push:
    branches: [main]

jobs:
  to_opencode:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps: # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Sync repo to OpenCoDE
        uses: wei/git-sync@v3
        with:
          source_repo: "digitalservicebund/digitalservicebund.github.io"
          source_branch: "main"
          destination_repo: "git@gitlab.opencode.de:digitalservicebund/digitalservicebund.git"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
