name: Sync to Open CoDE

concurrency: Sync

on:
  push:
    branches: [main]

jobs:
  to_opencode:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps: # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false   
      
      - name: Sync repo to OpenCoDE
        shell: bash
        run: |
          # Create ssh client config
          mkdir ~/.ssh
          cat <<EOF > ~/.ssh/config
          Host gitlab.opencode.de
            ServerAliveInterval 60
            ServerAliveCountMax 5
            KexAlgorithms ecdh-sha2-nistp521
          EOF
          
          # Add OpenCoDE host key
          ssh-keyscan gitlab.opencode.de > ~/.ssh/known_hosts
          
          # Start ssh-agent and add private key
          eval $(ssh-agent)
          echo "$SSH_KEY" | sed '$ s/\n$//' | ssh-add -
          
          # Push
          git remote add opencode git@gitlab.opencode.de:digitalservicebund/digitalservicebund.git
          git push opencode -f
        env:
          SSH_KEY: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
